[package]
name = "server"
version = "0.1.0"
edition = "2021"


[dependencies]
tokio = { version = "1.43", features = ["full"] }
thiserror = "2.0"

common = { path = "../common" }
bincode = "1.3"

async-trait = "0.1"
uuid = { version = "1.12.1", features = ["v4", "fast-rng"] }
