name: Test
on:
    push:
        branches: ["*"]
    pull_request:
        branches: ["*"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up ALSA configuration
              run: |
                  echo 'pcm.!default { type null }' > ~/.asoundrc
                  echo 'ctl.!default { type hw card 0 }' >> ~/.asoundrc
                  cat ~/.asoundrc  # Debug: Check the configuration
            - name: Update apt
              run: |
                  sudo apt-get update
                  sudo apt-get install -y alsa-utils
                  sudo apt-get install libasound2-dev libudev-dev
                  aplay -l  # List available devices
            - name: Install tar
              run: cargo install cargo-tarpaulin
            - name: Build
              run: cargo build --verbose
            - name: Generate coverage report
              run: cargo tarpaulin --out Xml
            - name: Code Coverage Summary Report
              uses: irongut/CodeCoverageSummary@v1.3.0
              with:
                  filename: cobertura.xml
                  badge: true
                  fail_below_min: 100
                  thresholds: 100

            - name: Add Coverage PR Comment
              uses: marocchino/sticky-pull-request-comment@v2
              if: github.event_name == 'pull_request'
              with:
                  recreate: true
                  path: code-coverage-results.md

            - name: Coveralls
              uses: coverallsapp/github-action@v2
              with:
                  path-to-lcov: ./cobertura.xml
                  format: cobertura
