name: Test
on:
    push:
        branches: ["*"]
    pull_request:
        branches: ["*"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install tar
              run: cargo install cargo-tarpaulin
            - name: Build
              run: cargo build --verbose
            - name: Generate coverage report
              run: cargo tarpaulin --out Xml
            - name: Code Coverage Summary Report
              uses: irongut/CodeCoverageSummary@v1.3.0
              with:
                  filename: cobertura.xml
                  badge: true
                  fail_below_min: 100
                  thresholds: 100

            - name: Coveralls
              uses: coverallsapp/github-action@v2
              with:
                  path-to-lcov: ./cobertura.xml
                  format: cobertura
