name: Test
on:
    push:
        branches: ["*"]
    pull_request:
        branches: ["*"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install tar
              run: cargo install cargo-tarpaulin
            - name: Build
              run: cargo build --verbose
            - name: Run tests
              run: RUSTFLAGS="-Cinstrument-coverage" cargo test --verbose
            - name: Generate coverage report
              run: cargo tarpaulin --out Xml
            - name: Code Coverage Summary Report
              uses: irongut/CodeCoverageSummary@v1.3.0
              with:
                  filename: cobertura.xml

            - name: Add Coverage PR Comment
              uses: marocchino/sticky-pull-request-comment@v2
              if: github.event_name == 'pull_request'
              with:
                  recreate: true
                  path: code-coverage-results.md
