name: Test
on:
    push:
        branches: ["*"]
    pull_request:
        branches: ["*"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: windows-2019
        steps:
            - uses: actions/checkout@v4

            - name: Audio device
              run: Get-CimInstance Win32_SoundDevice | fl *
            - run: "Invoke-WebRequest https://github.com/duncanthrax/scream/releases/download/4.0/Scream4.0.zip -OutFile Scream4.0.zip"
            - run: "Expand-Archive -Path Scream4.0.zip -DestinationPath Scream"
            # To work around https://github.com/duncanthrax/scream/issues/215, create our own self-signed certificate for the Scream driver.
            # makecert.exe insists on interactively asking the user for a password (sigh...), so use OpenSSL instead.
            # `-extensions v3_req` is a trick to make sure the resulting cert has basic constraint CA:FALSE (the default is CA:TRUE which is problematic here) without having to create an OpenSSL config file.
            - run: "openssl req -batch -verbose -x509 -newkey rsa -keyout ScreamCertificate.pvk -out ScreamCertificate.cer -nodes -extensions v3_req"
            - run: "openssl pkcs12 -export -nodes -in ScreamCertificate.cer -inkey ScreamCertificate.pvk -out ScreamCertificate.pfx -passout pass:"
            # This is just to make sure signtool.exe is in the PATH
            - uses: ilammy/msvc-dev-cmd@v1
            # Sign the driver with the self-signed certificate we just made.
            - run: 'signtool sign /v /fd SHA256 /f ScreamCertificate.pfx Scream\Install\driver\x64\Scream.cat'
            # Tell Windows to trust the self-signed certificate we just made.
            # (For some reason it has to be added to both stores for it to work.)
            - run: 'Import-Certificate -FilePath ScreamCertificate.cer -CertStoreLocation Cert:\LocalMachine\root'
            - run: 'Import-Certificate -FilePath ScreamCertificate.cer -CertStoreLocation Cert:\LocalMachine\TrustedPublisher'
            # Finally, install the driver.
            - run: 'Scream\Install\helpers\devcon-x64.exe install Scream\Install\driver\x64\Scream.inf *Scream'
              # For convenience, make sure we fail fast if for whatever reason the install gets blocked on some GUI prompt.
              timeout-minutes: 5
            - name: Audio device
              run: Get-CimInstance Win32_SoundDevice | fl *
            - name: Install tar
              run: cargo install cargo-tarpaulin
            - name: Build
              run: cargo build --verbose
            - name: Generate coverage report
              run: cargo tarpaulin --out Xml
            - name: Code Coverage Summary Report
              uses: irongut/CodeCoverageSummary@v1.3.0
              with:
                  filename: cobertura.xml
                  badge: true
                  fail_below_min: 100
                  thresholds: 100

            - name: Add Coverage PR Comment
              uses: marocchino/sticky-pull-request-comment@v2
              if: github.event_name == 'pull_request'
              with:
                  recreate: true
                  path: code-coverage-results.md

            - name: Coveralls
              uses: coverallsapp/github-action@v2
              with:
                  path-to-lcov: ./cobertura.xml
                  format: cobertura
