name: Test
on:
    push:
        branches: ["*"]
    pull_request:
        branches: ["*"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4

            - name: Audio device
              run: Get-CimInstance Win32_SoundDevice | fl *
            - name: Start audisvr
              run: net start audiosrv
            - name: Install Scream
              shell: powershell
              run: |
                  Invoke-WebRequest https://github.com/duncanthrax/scream/releases/download/3.8/Scream3.8.zip -OutFile Scream3.8.zip
                  Expand-Archive -Path Scream3.8.zip -DestinationPath Scream
                  Import-Certificate -FilePath Scream\Install\driver\x64\Scream.cat -CertStoreLocation Cert:\LocalMachine\TrustedPublisher 
                  Scream\Install\helpers\devcon-x64.exe install Scream\Install\driver\x64\Scream.inf *Scream
            - name: Audio device
              run: Get-CimInstance Win32_SoundDevice | fl *

            - name: Install llvm-cov
              run: cargo install cargo-llvm-cov
            - name: Build
              run: cargo build
            - name: Generate coverage report
              run: cargo llvm-cov --all-features --workspace --cobertura --output-path cobertura.xml --exclude app
            - name: Code Coverage Summary Report
              uses: irongut/CodeCoverageSummary@v1.3.0
              with:
                  filename: cobertura.xml
                  badge: true
                  fail_below_min: 100
                  thresholds: 100
                  hide_complexity: true
            - name: Coveralls
              uses: coverallsapp/github-action@v2
              with:
                  file: cobertura.xml
                  format: cobertura
